CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW `sales_order_combos`
AS SELECT
   `PS`.`qSalesOrders_PKEY` AS `qSalesOrders_PKEY`,
   `RS`.*,
   `PS`.`CreationTimeStamp` AS `CreationTimeStamp`,
   `PS`.`CreationUser` AS `CreationUser`,
   `PS`.`LastModificationTimeStamp` AS `LastModificationTimeStamp`,
   `PS`.`LastModificationUser` AS `LastModificationUser`,
   `PS`.`FK_Jobs_PKEY` AS `FK_Jobs_PKEY`,
   `PS`.`FK_Project_PKEY` AS `FK_Project_PKEY`,
   `PS`.`FK_qEstimates_PKEY` AS `FK_qEstimates_PKEY`,
   `PS`.`FK_Customers_PKEY` AS `FK_Customers_PKEY`,
   `PS`.`SO_Amount` AS `SO_Amount`,
   `PS`.`SO_ClientPOAmount` AS `SO_ClientPOAmount`,
   `PS`.`SO_ClientPODate` AS `SO_ClientPODate`,
   `PS`.`SO_ClientPONo` AS `SO_ClientPONo`,
   `PS`.`SO_ClientPOURL` AS `SO_ClientPOURL`,
   `PS`.`SO_ClientPOURL BU` AS `SO_ClientPOURL BU`,
   `PS`.`SO_DateCompleted_Actual` AS `SO_DateCompleted_Actual`,
   `PS`.`SO_DateCompleted_Estimated` AS `SO_DateCompleted_Estimated`,
   `PS`.`SO_DateCreated` AS `SO_DateCreated`,
   `PS`.`SO_DateFDOB` AS `SO_DateFDOB`,
   `PS`.`SO_DateStarted_Actual` AS `SO_DateStarted_Actual`,
   `PS`.`SO_DateStarted_Estimated` AS `SO_DateStarted_Estimated`,
   `PS`.`SO_Notes` AS `SO_Notes`,
   `PS`.`SO_Number` AS `SO_Number`,
   `PS`.`SO_PercentComplete` AS `SO_PercentComplete`,
   `PS`.`SO_ProjectForeman` AS `SO_ProjectForeman`,
   `PS`.`SO_ProjectManager` AS `SO_ProjectManager`,
   `PS`.`SO_Status` AS `SO_Status`,
   `PS`.`SO_URL` AS `SO_URL`,
   `PS`.`SO_URL BU` AS `SO_URL BU`,
   `PS`.`SO_MaterialsDateNeededBy` AS `SO_MaterialsDateNeededBy`,
   `PS`.`SO_MaterialsStatus` AS `SO_MaterialsStatus`,
   `PS`.`SO_LOM_URL` AS `SO_LOM_URL`,
   `PS`.`FK_ProgMan_Employees_PKEY` AS `FK_ProgMan_Employees_PKEY`,
   `PS`.`FK_TechLead_Employees_PKEY` AS `FK_TechLead_Employees_PKEY`,
   `PS`.`SO_Description` AS `SO_Description`
FROM (`railstest_development`.`sales_orders` `RS` left join `Thresher`.`qSalesOrders` `PS` on((concat('SO-',`RS`.`ref_number`) = `PS`.`SO_Number`)));