# clear quickbooks jobs
  requests = [{:time_tracking_add_rq => {:time_tracking_add => {:txn_date => "2017-12-11", :entity_ref => {:full_name => "Klerk, Nichole J"}, :customer_ref => {:full_name => "Google:Construction"}, :item_service_ref => {:full_name => "Video:0100"}, :duration => "PT8H0M0S", :payroll_item_wage_ref => {:full_name => "Hourly Level 1"},                                       :billable_status => "NotBillable"}}, }, {:time_tracking_add_rq => {:time_tracking_add => {:txn_date => "2017-12-12", :entity_ref => {:full_name => "Klerk, Nichole J"}, :customer_ref => {:full_name => "TCP:IT:P-903"}, :item_service_ref => {:full_name => "Video:0100"}, :duration => "PT8H0M0S", :payroll_item_wage_ref => {:full_name => "Hourly Level 1"},                        :billable_status => "NotBillable"}}, }, {:time_tracking_add_rq => {:time_tracking_add => {:txn_date => "2017-12-13", :entity_ref => {:full_name => "Klerk, Nichole J"}, :customer_ref => {:full_name => "TCP:IT"}, :item_service_ref => {:full_name => "Video:0100"}, :duration => "PT8H0M0S", :payroll_item_wage_ref => {:full_name => "Hourly Level 1"},                                       :billable_status => "NotBillable"}}, }, {:time_tracking_add_rq => {:time_tracking_add => {:txn_date => "2017-12-14", :entity_ref => {:full_name => "Klerk, Nichole J"}, :customer_ref => {:full_name => "TCP:IT:P-903"}, :item_service_ref => {:full_name => "Video:0100"}, :duration => "PT8H0M0S", :payroll_item_wage_ref => {:full_name => "Hourly Level 1"},                                       :billable_status => "NotBillable"}}, }, {:time_tracking_add_rq => {:time_tracking_add => {:txn_date => "2017-12-15", :entity_ref => {:full_name => "Klerk, Nichole J"}, :customer_ref => {:full_name => "TCP:IT:P-903"}, :item_service_ref => {:full_name => "Video:0100"}, :duration => "PT8H0M0S", :payroll_item_wage_ref => {:full_name => "Hourly Level 1"},                                       :billable_status => "NotBillable"}}, }]
  QBWC.clear_jobs
  QBWC.add_job(:initial, false, '', InitialWorker)
  QBWC.add_job(:query, false, '', QueryWorker)
  QBWC.add_job(:list_del, false, '', ListDeletedQueryWorker)
  QBWC.add_job(:txn_del, false, '', TxnDeletedQueryWorker)
  QBWC.add_job(:time_tracking_query, true, '', TimeTrackingQueryWorker)
  QBWC.add_job(:add_time, false, '', TimeTrackingAddWorker, requests)
  QBWC.add_job(:employee_query, false, '', EmployeeQueryWorker)

