class DropMergeTables < ActiveRecord::Migration[5.0]
  def change
    begin
    drop_table :Classes_Certs
    drop_table :Classes_Certs_Join_Req
    drop_table :Classes_Certs_List_Tier
    drop_table :ConstTracker
    drop_table :Customers
    drop_table :Deliveries
    drop_table :DeliveryItems
    drop_table :Departments
    drop_table :Employees
    drop_table :Employees_Badges
    drop_table :Employees_Cert
    drop_table :Employees_Cert_Todo
    drop_table :Employees_List_Size
    drop_table :Employees_List_Title
    drop_table :Employees_NDAs
    drop_table :Holidays
    drop_table :List_Salutation
    drop_table :Menu
    drop_table :PaymentMethod
    drop_table :Payments
    drop_table :Pictures
    drop_table :Project
    drop_table :ProjectCrew
    drop_table :ProjectEstimates
    drop_table :ProjectNoteTypes
    drop_table :ProjectRoleTypes
    drop_table :ProjectRoles
    drop_table :ProjectSiteAssessment
    drop_table :Project_List_Status
    drop_table :Project_Transactions
    drop_table :RMA
    drop_table :RMA_Assignment
    drop_table :RMA_AutoAssignment
    drop_table :RMA_AutoAssignment_Assignment
    drop_table :RMA_List_Escalation
    drop_table :RMA_List_Status
    drop_table :RMA_List_Type
    drop_table :RMA_Transactions
    drop_table :Review
    drop_table :Review_Answers
    drop_table :Review_Categories
    drop_table :Review_Questions
    drop_table :Review_Questions_Join_Titles
    drop_table :SalesLead_Transactions
    drop_table :Schedule
    drop_table :Skill_Assessment_Answers
    drop_table :Skill_Assessment_Cat1
    drop_table :Skill_Assessment_Cat2
    drop_table :Skill_Assessment_Cat3
    drop_table :Skill_Assessment_Cat4
    drop_table :Skill_Assessment_Questions
    drop_table :Skill_Assessment_Ranges
    drop_table :Skill_Assessment_Types
    drop_table :StartPage_Alert
    drop_table :Tickets
    drop_table :Tickets_Assignment
    drop_table :Tickets_AutoAssignment
    drop_table :Tickets_AutoAssignment_Assignment
    drop_table :Tickets_Email_Remind
    drop_table :Tickets_Flag
    drop_table :Tickets_List_Escalation
    drop_table :Tickets_List_Maint_Status
    drop_table :Tickets_List_Status
    drop_table :Tickets_List_Type
    drop_table :Tickets_Transactions
    drop_table :TimeCardTrans
    drop_table :TimeCards
    drop_table :TimePunch
    drop_table :Vendor
    drop_table :access_log
    drop_table :cts_answers
    drop_table :groups
    drop_table :inventory
    drop_table :job_phases
    drop_table :membership
    drop_table :menu_items
    drop_table :permissions
    drop_table :qDocuments
    drop_table :qDocuments_Transactions
    drop_table :qEstimates
    drop_table :qEstimates_Transactions
    drop_table :qInvoices
    drop_table :qInvoices_List_Status
    drop_table :qInvoices_List_Terms
    drop_table :qInvoices_List_Via
    drop_table :qInvoices_Log
    drop_table :qInvoices_Transactions
    drop_table :qPurchaseOrders
    drop_table :qPurchaseOrders_Transactions
    drop_table :qSalesOrders
    drop_table :qSalesOrdersTracker
    drop_table :qSalesOrders_List_Status
    drop_table :qSalesOrders_Transactions
    drop_table :qShipments
    drop_table :users
    rescue => e
      puts "#{e}"
    end
  end
end
